const REQUEST_USER = "GET_USER_INFORMATION";
const SET_USER_INFO = "SET_USER_INFORMATION";
const ERROR_USER_INFO = "ERROR_USER_INFO";


// USE TO MANAGE THE VARIOUS TABS
const SET_CURRENT_VIEW = "SET_CURRENT_VIEW";

// SET_HOME_TAB (TRENDING, NEW, HOT)
const SET_HOME_TAB = "SET_HOME_TAB";

// SET_VIEW_TAB (TRENDING, NEW, HOT) for a specific tab
const SET_VIEW_TAB = "SET_VIEW_TAB"

// KEY ACTIVITIES
// LOAD A NEW PAGE (NEXT|PREVIOUS)
const SET_NEW_PAGE = "SET_HOME_TAB";

const SET_CURRENT_POST = "SET_CURRENT_POST";