export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';
export const FETCH_POST = 'FETCH_POST';


// export const FETCH_NEW_POST = 'FETCH_NEW_POST';
// export const FETCH_HOT_POST = 'FETCH_HOT_POST';
// export const FETCH_TRENDING_POST = 'FETCH_TRENDING_POST';

// export const FETCH_USER_ACCOUNT = 'FETCH_USER_ACCOUNT';
// export const FETCH_USER_POSTS = 'FETCH_USER_POSTS';
// export const FETCH_USER_TRANSACTIONS = 'FETCH_USER_TRANSACTIONS';


// // REMEMBER THESE ARE CALLS BRUH
// export const SEND_LOGIN_USER = 'SEND_LOGIN_USER';
// export const SEND_REGISTER_USER = 'SEND_REGISTER_USER';